name: OnPublishedRelease
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          dotnet-quality: 'ga'
      - name: Restore dependencies
        working-directory: ./src
        run: |
          dotnet restore
      - name: Build
        working-directory: ./src
        run: |
          dotnet build --no-restore --configuration Release
      - name: Test
        working-directory: ./src
        run: |
          dotnet test --no-build --configuration Release --verbosity normal
      - name: Publish on nuget.org
        working-directory: ./src
        run: |
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
